	TARGET = ESP-T4-Weather


	IDF_PATH = $(HOME)/esp/esp-idf

	PROJECT_PATH = $(HOME)/Projects/ESP-T4-Weather


	include(esp.pri)

	INCLUDEPATH += \
			bootloader \
			bootloader/CMakeFiles/3.16.3/CompilerIdC \
			bootloader/CMakeFiles/3.16.3/CompilerIdCXX \
			bootloader/config \
			components/font_render \
			components/font_render/freetype2/builds/amiga/include/freetype/config \
			components/font_render/freetype2/builds/amiga/include \
			components/font_render/freetype2/builds/amiga/src/base \
			components/font_render/freetype2/builds/atari \
			components/font_render/freetype2/builds/mac \
			components/font_render/freetype2/builds/unix \
			components/font_render/freetype2/builds/vms \
			components/font_render/freetype2/builds/win32 \
			components/font_render/freetype2/builds/wince \
			components/font_render/freetype2/devel \
			components/font_render/freetype2/include/freetype/config \
			components/font_render/freetype2/include/freetype \
			components/font_render/freetype2/include/freetype/internal \
			components/font_render/freetype2/include/freetype/internal/services \
			components/font_render/freetype2/include \
			components/font_render/freetype2/src/autofit \
			components/font_render/freetype2/src/base \
			components/font_render/freetype2/src/bdf \
			components/font_render/freetype2/src/bzip2 \
			components/font_render/freetype2/src/cache \
			components/font_render/freetype2/src/cff \
			components/font_render/freetype2/src/cid \
			components/font_render/freetype2/src/gxvalid \
			components/font_render/freetype2/src/gzip \
			components/font_render/freetype2/src/lzw \
			components/font_render/freetype2/src/otvalid \
			components/font_render/freetype2/src/pcf \
			components/font_render/freetype2/src/pfr \
			components/font_render/freetype2/src/psaux \
			components/font_render/freetype2/src/pshinter \
			components/font_render/freetype2/src/psnames \
			components/font_render/freetype2/src/raster \
			components/font_render/freetype2/src/sfnt \
			components/font_render/freetype2/src/smooth \
			components/font_render/freetype2/src/tools \
			components/font_render/freetype2/src/tools/ftrandom \
			components/font_render/freetype2/src/truetype \
			components/font_render/freetype2/src/type1 \
			components/font_render/freetype2/src/type42 \
			components/font_render/freetype2/src/winfonts \
			components/font_render/include \
			components/font_render/include/freetype/config \
			components/hagl/include \
			components/hagl/src \
			components/hagl_hal/include \
			components/hagl_hal/src \
			config \
			esp-idf/mbedtls/mbedtls/include \
			esp-idf/mbedtls/mbedtls/include/CMakeFiles \
			kconfig_bin \
			main 

	SOURCES += \
			bootloader/CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.c \
			bootloader/CMakeFiles/3.16.3/CompilerIdCXX/CMakeCXXCompilerId.cpp \
			components/font_render/freetype2/src/gzip/adler32.c \
			components/font_render/freetype2/src/autofit/afangles.c \
			components/font_render/freetype2/src/autofit/afcjk.c \
			components/font_render/freetype2/src/autofit/afdummy.c \
			components/font_render/freetype2/src/autofit/afglobal.c \
			components/font_render/freetype2/src/autofit/afhints.c \
			components/font_render/freetype2/src/autofit/afindic.c \
			components/font_render/freetype2/src/autofit/aflatin.c \
			components/font_render/freetype2/src/autofit/aflatin2.c \
			components/font_render/freetype2/src/autofit/afloader.c \
			components/font_render/freetype2/src/autofit/afmodule.c \
			components/font_render/freetype2/src/psaux/afmparse.c \
			components/font_render/freetype2/src/autofit/afpic.c \
			components/font_render/freetype2/src/autofit/afwarp.c \
			components/font_render/freetype2/src/tools/apinames.c \
			components/font_render/freetype2/src/autofit/autofit.c \
			components/font_render/freetype2/src/base/basepic.c \
			components/font_render/freetype2/src/bdf/bdf.c \
			components/font_render/freetype2/src/bdf/bdfdrivr.c \
			components/font_render/freetype2/src/bdf/bdflib.c \
			components/hagl/src/bitmap.c \
			components/font_render/freetype2/src/cff/cf2arrst.c \
			components/font_render/freetype2/src/cff/cf2blues.c \
			components/font_render/freetype2/src/cff/cf2error.c \
			components/font_render/freetype2/src/cff/cf2font.c \
			components/font_render/freetype2/src/cff/cf2ft.c \
			components/font_render/freetype2/src/cff/cf2hints.c \
			components/font_render/freetype2/src/cff/cf2intrp.c \
			components/font_render/freetype2/src/cff/cf2read.c \
			components/font_render/freetype2/src/cff/cf2stack.c \
			components/font_render/freetype2/src/cff/cff.c \
			components/font_render/freetype2/src/cff/cffcmap.c \
			components/font_render/freetype2/src/cff/cffdrivr.c \
			components/font_render/freetype2/src/cff/cffgload.c \
			components/font_render/freetype2/src/cff/cffload.c \
			components/font_render/freetype2/src/cff/cffobjs.c \
			components/font_render/freetype2/src/cff/cffparse.c \
			components/font_render/freetype2/src/cff/cffpic.c \
			components/font_render/freetype2/src/cid/cidgload.c \
			components/font_render/freetype2/src/cid/cidload.c \
			components/font_render/freetype2/src/cid/cidobjs.c \
			components/font_render/freetype2/src/cid/cidparse.c \
			components/font_render/freetype2/src/cid/cidriver.c \
			components/hagl/src/clip.c \
			components/font_render/font_render.c \
			components/hagl/src/fontx.c \
			components/hagl/src/fontx2.c \
			components/font_render/freetype2/src/base/ftadvanc.c \
			components/font_render/freetype2/src/base/ftapi.c \
			components/font_render/freetype2/src/base/ftbase.c \
			components/font_render/freetype2/src/base/ftbbox.c \
			components/font_render/freetype2/src/base/ftbdf.c \
			components/font_render/freetype2/src/base/ftbitmap.c \
			components/font_render/freetype2/src/bzip2/ftbzip2.c \
			components/font_render/freetype2/src/cache/ftcache.c \
			components/font_render/freetype2/src/base/ftcalc.c \
			components/font_render/freetype2/src/cache/ftcbasic.c \
			components/font_render/freetype2/src/cache/ftccache.c \
			components/font_render/freetype2/src/cache/ftccmap.c \
			components/font_render/freetype2/src/cache/ftcglyph.c \
			components/font_render/freetype2/src/base/ftcid.c \
			components/font_render/freetype2/src/cache/ftcimage.c \
			components/font_render/freetype2/src/cache/ftcmanag.c \
			components/font_render/freetype2/src/cache/ftcmru.c \
			components/font_render/freetype2/src/cache/ftcsbits.c \
			components/font_render/freetype2/src/base/ftdbgmem.c \
			components/font_render/freetype2/src/base/ftdebug.c \
			components/font_render/freetype2/builds/wince/ftdebug.c \
			components/font_render/freetype2/builds/win32/ftdebug.c \
			components/font_render/freetype2/builds/amiga/src/base/ftdebug.c \
			components/font_render/freetype2/src/base/ftfstype.c \
			components/font_render/freetype2/src/base/ftgasp.c \
			components/font_render/freetype2/src/base/ftgloadr.c \
			components/font_render/freetype2/src/base/ftglyph.c \
			components/font_render/freetype2/src/smooth/ftgrays.c \
			components/font_render/freetype2/src/base/ftgxval.c \
			components/font_render/freetype2/src/gzip/ftgzip.c \
			components/font_render/freetype2/src/base/ftinit.c \
			components/font_render/freetype2/src/base/ftlcdfil.c \
			components/font_render/freetype2/src/lzw/ftlzw.c \
			components/font_render/freetype2/src/base/ftmac.c \
			components/font_render/freetype2/builds/mac/ftmac.c \
			components/font_render/freetype2/src/base/ftmm.c \
			components/font_render/freetype2/src/base/ftobjs.c \
			components/font_render/freetype2/src/base/ftotval.c \
			components/font_render/freetype2/src/base/ftoutln.c \
			components/font_render/freetype2/src/base/ftpatent.c \
			components/font_render/freetype2/src/base/ftpfr.c \
			components/font_render/freetype2/src/base/ftpic.c \
			components/font_render/freetype2/src/tools/ftrandom/ftrandom.c \
			components/font_render/freetype2/src/raster/ftraster.c \
			components/font_render/freetype2/src/raster/ftrend1.c \
			components/font_render/freetype2/src/base/ftrfork.c \
			components/font_render/freetype2/src/smooth/ftsmooth.c \
			components/font_render/freetype2/src/base/ftsnames.c \
			components/font_render/freetype2/src/smooth/ftspic.c \
			components/font_render/freetype2/src/base/ftstream.c \
			components/font_render/freetype2/src/base/ftstroke.c \
			components/font_render/freetype2/src/base/ftsynth.c \
			components/font_render/freetype2/src/base/ftsystem.c \
			components/font_render/freetype2/builds/vms/ftsystem.c \
			components/font_render/freetype2/builds/unix/ftsystem.c \
			components/font_render/freetype2/builds/amiga/src/base/ftsystem.c \
			components/font_render/freetype2/src/base/fttrigon.c \
			components/font_render/freetype2/src/base/fttype1.c \
			components/font_render/freetype2/src/base/ftutil.c \
			components/font_render/freetype2/src/base/ftwinfnt.c \
			components/font_render/freetype2/src/base/ftxf86.c \
			components/font_render/freetype2/src/lzw/ftzopen.c \
			components/font_render/freetype2/src/gxvalid/gxvalid.c \
			components/font_render/freetype2/src/gxvalid/gxvbsln.c \
			components/font_render/freetype2/src/gxvalid/gxvcommn.c \
			components/font_render/freetype2/src/gxvalid/gxvfeat.c \
			components/font_render/freetype2/src/gxvalid/gxvfgen.c \
			components/font_render/freetype2/src/gxvalid/gxvjust.c \
			components/font_render/freetype2/src/gxvalid/gxvkern.c \
			components/font_render/freetype2/src/gxvalid/gxvlcar.c \
			components/font_render/freetype2/src/gxvalid/gxvmod.c \
			components/font_render/freetype2/src/gxvalid/gxvmort.c \
			components/font_render/freetype2/src/gxvalid/gxvmort0.c \
			components/font_render/freetype2/src/gxvalid/gxvmort1.c \
			components/font_render/freetype2/src/gxvalid/gxvmort2.c \
			components/font_render/freetype2/src/gxvalid/gxvmort4.c \
			components/font_render/freetype2/src/gxvalid/gxvmort5.c \
			components/font_render/freetype2/src/gxvalid/gxvmorx.c \
			components/font_render/freetype2/src/gxvalid/gxvmorx0.c \
			components/font_render/freetype2/src/gxvalid/gxvmorx1.c \
			components/font_render/freetype2/src/gxvalid/gxvmorx2.c \
			components/font_render/freetype2/src/gxvalid/gxvmorx4.c \
			components/font_render/freetype2/src/gxvalid/gxvmorx5.c \
			components/font_render/freetype2/src/gxvalid/gxvopbd.c \
			components/font_render/freetype2/src/gxvalid/gxvprop.c \
			components/font_render/freetype2/src/gxvalid/gxvtrak.c \
			components/hagl/src/hagl.c \
			components/hagl_hal/src/hagl_hal_double.c \
			components/hagl_hal/src/hagl_hal_single.c \
			components/hagl_hal/src/hagl_hal_triple.c \
			main/hagl_util.c \
			components/hagl/src/hsl.c \
			components/font_render/freetype2/src/gzip/infblock.c \
			components/font_render/freetype2/src/gzip/infcodes.c \
			components/font_render/freetype2/src/gzip/inflate.c \
			components/font_render/freetype2/src/gzip/inftrees.c \
			components/font_render/freetype2/src/gzip/infutil.c \
			main/main.c \
			components/font_render/freetype2/src/base/md5.c \
			components/hagl_hal/src/mipi_display.c \
			components/font_render/freetype2/src/otvalid/otvalid.c \
			components/font_render/freetype2/src/otvalid/otvbase.c \
			components/font_render/freetype2/src/otvalid/otvcommn.c \
			components/font_render/freetype2/src/otvalid/otvgdef.c \
			components/font_render/freetype2/src/otvalid/otvgpos.c \
			components/font_render/freetype2/src/otvalid/otvgsub.c \
			components/font_render/freetype2/src/otvalid/otvjstf.c \
			components/font_render/freetype2/src/otvalid/otvmath.c \
			components/font_render/freetype2/src/otvalid/otvmod.c \
			components/font_render/freetype2/src/pcf/pcf.c \
			components/font_render/freetype2/src/pcf/pcfdrivr.c \
			components/font_render/freetype2/src/pcf/pcfread.c \
			components/font_render/freetype2/src/pcf/pcfutil.c \
			components/font_render/freetype2/src/pfr/pfr.c \
			components/font_render/freetype2/src/pfr/pfrcmap.c \
			components/font_render/freetype2/src/pfr/pfrdrivr.c \
			components/font_render/freetype2/src/pfr/pfrgload.c \
			components/font_render/freetype2/src/pfr/pfrload.c \
			components/font_render/freetype2/src/pfr/pfrobjs.c \
			components/font_render/freetype2/src/pfr/pfrsbit.c \
			bootloader/project_elf_src.c \
			components/font_render/freetype2/src/psaux/psaux.c \
			components/font_render/freetype2/src/psaux/psauxmod.c \
			components/font_render/freetype2/src/psaux/psconv.c \
			components/font_render/freetype2/src/pshinter/pshalgo.c \
			components/font_render/freetype2/src/pshinter/pshglob.c \
			components/font_render/freetype2/src/pshinter/pshinter.c \
			components/font_render/freetype2/src/pshinter/pshmod.c \
			components/font_render/freetype2/src/pshinter/pshpic.c \
			components/font_render/freetype2/src/pshinter/pshrec.c \
			components/font_render/freetype2/src/psnames/psmodule.c \
			components/font_render/freetype2/src/psnames/psnames.c \
			components/font_render/freetype2/src/psaux/psobjs.c \
			components/font_render/freetype2/src/psnames/pspic.c \
			components/font_render/freetype2/src/raster/raster.c \
			components/font_render/freetype2/src/raster/rastpic.c \
			components/hagl/src/rgb565.c \
			components/hagl/src/rgb888.c \
			components/font_render/freetype2/src/sfnt/sfdriver.c \
			components/font_render/freetype2/src/sfnt/sfnt.c \
			components/font_render/freetype2/src/sfnt/sfntpic.c \
			components/font_render/freetype2/src/sfnt/sfobjs.c \
			components/font_render/freetype2/src/smooth/smooth.c \
			components/font_render/freetype2/src/type1/t1afm.c \
			components/font_render/freetype2/src/psaux/t1cmap.c \
			components/font_render/freetype2/src/psaux/t1decode.c \
			components/font_render/freetype2/src/type1/t1driver.c \
			components/font_render/freetype2/src/type1/t1gload.c \
			components/font_render/freetype2/src/type1/t1load.c \
			components/font_render/freetype2/src/type1/t1objs.c \
			components/font_render/freetype2/src/type1/t1parse.c \
			components/font_render/freetype2/src/type42/t42drivr.c \
			components/font_render/freetype2/src/type42/t42objs.c \
			components/font_render/freetype2/src/type42/t42parse.c \
			components/font_render/freetype2/src/tools/test_afm.c \
			components/font_render/freetype2/src/tools/test_bbox.c \
			components/font_render/freetype2/src/tools/test_trig.c \
			components/hagl/src/tjpgd.c \
			components/font_render/freetype2/src/truetype/truetype.c \
			components/font_render/freetype2/src/sfnt/ttbdf.c \
			components/font_render/freetype2/src/sfnt/ttcmap.c \
			components/font_render/freetype2/src/truetype/ttdriver.c \
			components/font_render/freetype2/src/truetype/ttgload.c \
			components/font_render/freetype2/src/truetype/ttgxvar.c \
			components/font_render/freetype2/src/truetype/ttinterp.c \
			components/font_render/freetype2/src/sfnt/ttkern.c \
			components/font_render/freetype2/src/sfnt/ttload.c \
			components/font_render/freetype2/src/sfnt/ttmtx.c \
			components/font_render/freetype2/src/truetype/ttobjs.c \
			components/font_render/freetype2/src/truetype/ttpic.c \
			components/font_render/freetype2/src/truetype/ttpload.c \
			components/font_render/freetype2/src/sfnt/ttpost.c \
			components/font_render/freetype2/src/sfnt/ttsbit.c \
			components/font_render/freetype2/src/sfnt/ttsbit0.c \
			components/font_render/freetype2/src/truetype/ttsubpix.c \
			components/font_render/freetype2/src/type1/type1.c \
			components/font_render/freetype2/src/cid/type1cid.c \
			components/font_render/freetype2/src/type42/type42.c \
			main/unicode.c \
			components/font_render/freetype2/src/winfonts/winfnt.c \
			kconfig_bin/zconf.hash.c \
			kconfig_bin/zconf.lex.c \
			kconfig_bin/zconf.tab.c \
			components/font_render/freetype2/src/gzip/zutil.c \ 
    components/hagl_hal/src/hagl_hal_triple.c \
    components/hagl_hal/src/mipi_display.c

	HEADERS += \
			components/font_render/freetype2/src/autofit/afangles.h \
			components/font_render/freetype2/src/autofit/afcjk.h \
			components/font_render/freetype2/src/autofit/afdummy.h \
			components/font_render/freetype2/src/autofit/aferrors.h \
			components/font_render/freetype2/src/autofit/afglobal.h \
			components/font_render/freetype2/src/autofit/afhints.h \
			components/font_render/freetype2/src/autofit/afindic.h \
			components/font_render/freetype2/src/autofit/aflatin.h \
			components/font_render/freetype2/src/autofit/aflatin2.h \
			components/font_render/freetype2/src/autofit/afloader.h \
			components/font_render/freetype2/src/autofit/afmodule.h \
			components/font_render/freetype2/src/psaux/afmparse.h \
			components/font_render/freetype2/src/autofit/afpic.h \
			components/font_render/freetype2/src/autofit/aftypes.h \
			components/font_render/freetype2/src/autofit/afwarp.h \
			components/hagl/include/aps.h \
			components/font_render/freetype2/include/freetype/internal/autohint.h \
			components/font_render/freetype2/src/base/basepic.h \
			components/font_render/freetype2/src/bdf/bdf.h \
			components/font_render/freetype2/src/bdf/bdfdrivr.h \
			components/font_render/freetype2/src/bdf/bdferror.h \
			components/hagl/include/bitmap.h \
			components/font_render/freetype2/src/cff/cf2arrst.h \
			components/font_render/freetype2/src/cff/cf2blues.h \
			components/font_render/freetype2/src/cff/cf2error.h \
			components/font_render/freetype2/src/cff/cf2fixed.h \
			components/font_render/freetype2/src/cff/cf2font.h \
			components/font_render/freetype2/src/cff/cf2ft.h \
			components/font_render/freetype2/src/cff/cf2glue.h \
			components/font_render/freetype2/src/cff/cf2hints.h \
			components/font_render/freetype2/src/cff/cf2intrp.h \
			components/font_render/freetype2/src/cff/cf2read.h \
			components/font_render/freetype2/src/cff/cf2stack.h \
			components/font_render/freetype2/src/cff/cf2types.h \
			components/font_render/freetype2/src/cff/cffcmap.h \
			components/font_render/freetype2/src/cff/cffdrivr.h \
			components/font_render/freetype2/src/cff/cfferrs.h \
			components/font_render/freetype2/src/cff/cffgload.h \
			components/font_render/freetype2/src/cff/cffload.h \
			components/font_render/freetype2/src/cff/cffobjs.h \
			components/font_render/freetype2/src/cff/cffparse.h \
			components/font_render/freetype2/src/cff/cffpic.h \
			components/font_render/freetype2/src/cff/cfftoken.h \
			components/font_render/freetype2/src/cff/cfftypes.h \
			components/font_render/freetype2/src/cid/ciderrs.h \
			components/font_render/freetype2/src/cid/cidgload.h \
			components/font_render/freetype2/src/cid/cidload.h \
			components/font_render/freetype2/src/cid/cidobjs.h \
			components/font_render/freetype2/src/cid/cidparse.h \
			components/font_render/freetype2/src/cid/cidriver.h \
			components/font_render/freetype2/src/cid/cidtoken.h \
			components/hagl/include/clip.h \
			components/hagl/include/config.h \
			components/font_render/freetype2/src/winfonts/fnterrs.h \
			components/hagl/include/font5x7.h \
			components/hagl/include/font5x8.h \
			components/hagl/include/font6x9.h \
			components/font_render/include/font_render.h \
			components/hagl/include/fontx.h \
			components/hagl/include/fontx2.h \
			components/hagl/include/fps.h \
			components/font_render/freetype2/include/freetype/freetype.h \
			components/font_render/freetype2/include/ft2build.h \
			components/font_render/freetype2/builds/unix/ft2unix.h \
			components/font_render/freetype2/include/freetype/ftadvanc.h \
			components/font_render/freetype2/include/freetype/ftautoh.h \
			components/font_render/freetype2/src/base/ftbase.h \
			components/font_render/freetype2/include/freetype/ftbbox.h \
			components/font_render/freetype2/include/freetype/ftbdf.h \
			components/font_render/freetype2/include/freetype/ftbitmap.h \
			components/font_render/freetype2/include/freetype/ftbzip2.h \
			components/font_render/freetype2/include/freetype/ftcache.h \
			components/font_render/freetype2/include/freetype/internal/ftcalc.h \
			components/font_render/freetype2/src/cache/ftccache.h \
			components/font_render/freetype2/src/cache/ftccback.h \
			components/font_render/freetype2/src/cache/ftcerror.h \
			components/font_render/freetype2/include/freetype/ftcffdrv.h \
			components/font_render/freetype2/src/cache/ftcglyph.h \
			components/font_render/freetype2/include/freetype/ftchapters.h \
			components/font_render/freetype2/include/freetype/ftcid.h \
			components/font_render/freetype2/src/cache/ftcimage.h \
			components/font_render/freetype2/src/cache/ftcmanag.h \
			components/font_render/freetype2/src/cache/ftcmru.h \
			components/font_render/include/freetype/config/ftconfig.h \
			components/font_render/freetype2/src/cache/ftcsbits.h \
			components/font_render/freetype2/include/freetype/internal/ftdebug.h \
			components/font_render/freetype2/include/freetype/internal/ftdriver.h \
			components/font_render/freetype2/include/freetype/fterrdef.h \
			components/font_render/freetype2/include/freetype/fterrors.h \
			components/font_render/freetype2/include/freetype/ftgasp.h \
			components/font_render/freetype2/include/freetype/internal/ftgloadr.h \
			components/font_render/freetype2/include/freetype/ftglyph.h \
			components/font_render/freetype2/src/smooth/ftgrays.h \
			components/font_render/freetype2/include/freetype/ftgxval.h \
			components/font_render/freetype2/include/freetype/ftgzip.h \
			components/font_render/include/freetype/config/ftheader.h \
			components/font_render/freetype2/include/freetype/ftimage.h \
			components/font_render/freetype2/include/freetype/ftincrem.h \
			components/font_render/freetype2/include/freetype/ftlcdfil.h \
			components/font_render/freetype2/include/freetype/ftlist.h \
			components/font_render/freetype2/include/freetype/ftlzw.h \
			components/font_render/freetype2/include/freetype/ftmac.h \
			components/font_render/freetype2/include/freetype/internal/ftmemory.h \
			components/font_render/freetype2/src/raster/ftmisc.h \
			components/font_render/freetype2/include/freetype/ftmm.h \
			components/font_render/freetype2/include/freetype/ftmodapi.h \
			components/font_render/freetype2/include/freetype/ftmoderr.h \
			components/font_render/include/freetype/config/ftmodule.h \
			components/font_render/freetype2/include/freetype/internal/ftobjs.h \
			components/font_render/include/freetype/config/ftoption.h \
			components/font_render/freetype2/include/freetype/ftotval.h \
			components/font_render/freetype2/include/freetype/ftoutln.h \
			components/font_render/freetype2/include/freetype/ftpfr.h \
			components/font_render/freetype2/include/freetype/internal/ftpic.h \
			components/font_render/freetype2/src/raster/ftraster.h \
			components/font_render/freetype2/src/raster/ftrend1.h \
			components/font_render/freetype2/include/freetype/ftrender.h \
			components/font_render/freetype2/include/freetype/internal/ftrfork.h \
			components/font_render/freetype2/include/freetype/internal/ftserv.h \
			components/font_render/freetype2/include/freetype/ftsizes.h \
			components/font_render/freetype2/src/smooth/ftsmerrs.h \
			components/font_render/freetype2/src/smooth/ftsmooth.h \
			components/font_render/freetype2/include/freetype/ftsnames.h \
			components/font_render/freetype2/src/smooth/ftspic.h \
			components/font_render/include/freetype/config/ftstdlib.h \
			components/font_render/freetype2/include/freetype/internal/ftstream.h \
			components/font_render/freetype2/include/freetype/ftstroke.h \
			components/font_render/freetype2/include/freetype/ftsynth.h \
			components/font_render/freetype2/include/freetype/ftsystem.h \
			components/font_render/freetype2/include/freetype/internal/fttrace.h \
			components/font_render/freetype2/include/freetype/fttrigon.h \
			components/font_render/freetype2/include/freetype/fttypes.h \
			components/font_render/freetype2/include/freetype/internal/ftvalid.h \
			components/font_render/freetype2/include/freetype/ftwinfnt.h \
			components/font_render/freetype2/include/freetype/ftxf86.h \
			components/font_render/freetype2/src/lzw/ftzopen.h \
			components/font_render/freetype2/src/gxvalid/gxvalid.h \
			components/font_render/freetype2/src/gxvalid/gxvcommn.h \
			components/font_render/freetype2/src/gxvalid/gxverror.h \
			components/font_render/freetype2/src/gxvalid/gxvfeat.h \
			components/font_render/freetype2/src/gxvalid/gxvmod.h \
			components/font_render/freetype2/src/gxvalid/gxvmort.h \
			components/font_render/freetype2/src/gxvalid/gxvmorx.h \
			components/hagl/include/hagl.h \
			components/hagl_hal/include/hagl_hal.h \
			components/hagl_hal/include/hagl_hal_double.h \
			components/hagl_hal/include/hagl_hal_single.h \
			components/hagl_hal/include/hagl_hal_triple.h \
			main/hagl_util.h \
			components/hagl/include/hsl.h \
			components/font_render/freetype2/src/gzip/infblock.h \
			components/font_render/freetype2/src/gzip/infcodes.h \
			components/font_render/freetype2/src/gzip/inffixed.h \
			components/font_render/freetype2/src/gzip/inftrees.h \
			components/font_render/freetype2/src/gzip/infutil.h \
			components/font_render/freetype2/include/freetype/internal/internal.h \
			components/font_render/freetype2/src/base/md5.h \
			components/hagl_hal/include/mipi_dcs.h \
			components/hagl_hal/include/mipi_display.h \
			components/font_render/freetype2/src/otvalid/otvalid.h \
			components/font_render/freetype2/src/otvalid/otvcommn.h \
			components/font_render/freetype2/src/otvalid/otverror.h \
			components/font_render/freetype2/src/otvalid/otvgpos.h \
			components/font_render/freetype2/src/otvalid/otvmod.h \
			components/font_render/freetype2/src/pcf/pcf.h \
			components/font_render/freetype2/src/pcf/pcfdrivr.h \
			components/font_render/freetype2/src/pcf/pcferror.h \
			components/font_render/freetype2/src/pcf/pcfread.h \
			components/font_render/freetype2/src/pcf/pcfutil.h \
			components/font_render/freetype2/src/pfr/pfrcmap.h \
			components/font_render/freetype2/src/pfr/pfrdrivr.h \
			components/font_render/freetype2/src/pfr/pfrerror.h \
			components/font_render/freetype2/src/pfr/pfrgload.h \
			components/font_render/freetype2/src/pfr/pfrload.h \
			components/font_render/freetype2/src/pfr/pfrobjs.h \
			components/font_render/freetype2/src/pfr/pfrsbit.h \
			components/font_render/freetype2/src/pfr/pfrtypes.h \
			components/font_render/freetype2/include/freetype/internal/psaux.h \
			components/font_render/freetype2/src/psaux/psauxerr.h \
			components/font_render/freetype2/src/psaux/psauxmod.h \
			components/font_render/freetype2/src/psaux/psconv.h \
			components/font_render/freetype2/src/pshinter/pshalgo.h \
			components/font_render/freetype2/src/pshinter/pshglob.h \
			components/font_render/freetype2/include/freetype/internal/pshints.h \
			components/font_render/freetype2/src/pshinter/pshmod.h \
			components/font_render/freetype2/src/pshinter/pshnterr.h \
			components/font_render/freetype2/src/pshinter/pshpic.h \
			components/font_render/freetype2/src/pshinter/pshrec.h \
			components/font_render/freetype2/src/psnames/psmodule.h \
			components/font_render/freetype2/src/psnames/psnamerr.h \
			components/font_render/freetype2/src/psaux/psobjs.h \
			components/font_render/freetype2/src/psnames/pspic.h \
			components/font_render/freetype2/src/psnames/pstables.h \
			components/font_render/freetype2/src/raster/rasterrs.h \
			components/font_render/freetype2/src/raster/rastpic.h \
			components/hagl/include/rgb332.h \
			components/hagl/include/rgb565.h \
			components/hagl/include/rgb888.h \
			config/sdkconfig.h \
			components/font_render/freetype2/src/sfnt/sfdriver.h \
			components/font_render/freetype2/src/sfnt/sferrors.h \
			components/font_render/freetype2/include/freetype/internal/sfnt.h \
			components/font_render/freetype2/src/sfnt/sfntpic.h \
			components/font_render/freetype2/src/sfnt/sfobjs.h \
			components/font_render/freetype2/include/freetype/internal/services/svbdf.h \
			components/font_render/freetype2/include/freetype/internal/services/svcid.h \
			components/font_render/freetype2/include/freetype/internal/services/svgldict.h \
			components/font_render/freetype2/include/freetype/internal/services/svgxval.h \
			components/font_render/freetype2/include/freetype/internal/services/svkern.h \
			components/font_render/freetype2/include/freetype/internal/services/svmm.h \
			components/font_render/freetype2/include/freetype/internal/services/svotval.h \
			components/font_render/freetype2/include/freetype/internal/services/svpfr.h \
			components/font_render/freetype2/include/freetype/internal/services/svpostnm.h \
			components/font_render/freetype2/include/freetype/internal/services/svprop.h \
			components/font_render/freetype2/include/freetype/internal/services/svpscmap.h \
			components/font_render/freetype2/include/freetype/internal/services/svpsinfo.h \
			components/font_render/freetype2/include/freetype/internal/services/svsfnt.h \
			components/font_render/freetype2/include/freetype/internal/services/svttcmap.h \
			components/font_render/freetype2/include/freetype/internal/services/svtteng.h \
			components/font_render/freetype2/include/freetype/internal/services/svttglyf.h \
			components/font_render/freetype2/include/freetype/internal/services/svwinfnt.h \
			components/font_render/freetype2/include/freetype/internal/services/svxf86nm.h \
			components/font_render/freetype2/src/type1/t1afm.h \
			components/font_render/freetype2/src/psaux/t1cmap.h \
			components/font_render/freetype2/src/psaux/t1decode.h \
			components/font_render/freetype2/src/type1/t1driver.h \
			components/font_render/freetype2/src/type1/t1errors.h \
			components/font_render/freetype2/src/type1/t1gload.h \
			components/font_render/freetype2/src/type1/t1load.h \
			components/font_render/freetype2/src/type1/t1objs.h \
			components/font_render/freetype2/src/type1/t1parse.h \
			components/font_render/freetype2/include/freetype/t1tables.h \
			components/font_render/freetype2/src/type1/t1tokens.h \
			components/font_render/freetype2/include/freetype/internal/t1types.h \
			components/font_render/freetype2/src/type42/t42drivr.h \
			components/font_render/freetype2/src/type42/t42error.h \
			components/font_render/freetype2/src/type42/t42objs.h \
			components/font_render/freetype2/src/type42/t42parse.h \
			components/font_render/freetype2/src/type42/t42types.h \
			components/hagl/include/tjpgd.h \
			components/font_render/freetype2/src/sfnt/ttbdf.h \
			components/font_render/freetype2/src/sfnt/ttcmap.h \
			components/font_render/freetype2/src/sfnt/ttcmapc.h \
			components/font_render/freetype2/src/truetype/ttdriver.h \
			components/font_render/freetype2/src/truetype/tterrors.h \
			components/font_render/freetype2/src/truetype/ttgload.h \
			components/font_render/freetype2/src/truetype/ttgxvar.h \
			components/font_render/freetype2/src/truetype/ttinterp.h \
			components/font_render/freetype2/src/sfnt/ttkern.h \
			components/font_render/freetype2/src/sfnt/ttload.h \
			components/font_render/freetype2/src/sfnt/ttmtx.h \
			components/font_render/freetype2/include/freetype/ttnameid.h \
			components/font_render/freetype2/src/truetype/ttobjs.h \
			components/font_render/freetype2/src/truetype/ttpic.h \
			components/font_render/freetype2/src/truetype/ttpload.h \
			components/font_render/freetype2/src/sfnt/ttpost.h \
			components/font_render/freetype2/src/sfnt/ttsbit.h \
			components/font_render/freetype2/src/truetype/ttsubpix.h \
			components/font_render/freetype2/include/freetype/tttables.h \
			components/font_render/freetype2/include/freetype/tttags.h \
			components/font_render/freetype2/include/freetype/internal/tttypes.h \
			components/font_render/freetype2/include/freetype/ttunpat.h \
			main/unicode.h \
			components/hagl/include/window.h \
			components/font_render/freetype2/src/winfonts/winfnt.h \
			components/font_render/freetype2/src/gzip/zconf.h \
			components/font_render/freetype2/src/gzip/zlib.h \
			components/font_render/freetype2/src/gzip/zutil.h 

	OTHER_FILES += \
			CMakeLists.txt \
			sdkconfig \
			sdkconfig.old \
			sdkconfig.ttgo-t4-v13 \
			main/CMakeLists.txt \
			components/hagl_hal/CMakeLists.txt \
			components/hagl/CMakeLists.txt \
			components/font_render/CMakeLists.txt \
			components/font_render/freetype2/src/tools/ftrandom/README \
			components/font_render/freetype2/src/pcf/README \
			components/font_render/freetype2/src/gxvalid/README \
			components/font_render/freetype2/src/bdf/README \
			components/font_render/freetype2/README \
			components/font_render/freetype2/objs/README \
			components/font_render/freetype2/docs/reference/README \
			components/font_render/freetype2/builds/mac/README \
			components/font_render/freetype2/builds/amiga/README \
			components/font_render/freetype2/builds/atari/README.TXT \
			components/font_render/freetype2/README.git \
			components/hagl_hal/README.md \
			components/hagl/README.md \
			config/sdkconfig.cmake \
			bootloader/config/sdkconfig.cmake \
			config/sdkconfig.json \
			bootloader/config/sdkconfig.json 

	DEFINES+=	CONFIG_ADC2_DISABLE_DAC=y \
			CONFIG_ADC_CAL_EFUSE_TP_ENABLE=y \
			CONFIG_ADC_CAL_EFUSE_VREF_ENABLE=y \
			CONFIG_ADC_CAL_LUT_ENABLE=y \
			CONFIG_ADC_DISABLE_DAC=y \
			CONFIG_APP_COMPILE_TIME_DATE=y \
			CONFIG_APP_RETRIEVE_LEN_ELF_SHA=16 \
			CONFIG_BOOTLOADER_LOG_LEVEL=3 \
			CONFIG_BOOTLOADER_LOG_LEVEL_INFO=y \
			CONFIG_BOOTLOADER_VDDSDIO_BOOST_1_9V=y \
			CONFIG_BOOTLOADER_WDT_ENABLE=y \
			CONFIG_BOOTLOADER_WDT_TIME_MS=9000 \
			CONFIG_BROWNOUT_DET=y \
			CONFIG_BROWNOUT_DET_LVL=0 \
			CONFIG_BROWNOUT_DET_LVL_SEL_0=y \
			CONFIG_BTDM_BLE_SLEEP_CLOCK_ACCURACY_INDEX_EFF=1 \
			CONFIG_BTDM_CONTROLLER_BLE_MAX_CONN_EFF=0 \
			CONFIG_BTDM_CONTROLLER_BR_EDR_MAX_ACL_CONN_EFF=0 \
			CONFIG_BTDM_CONTROLLER_BR_EDR_MAX_SYNC_CONN_EFF=0 \
			CONFIG_BTDM_CONTROLLER_PINNED_TO_CORE=0 \
			CONFIG_BTDM_CTRL_BLE_MAX_CONN_EFF=0 \
			CONFIG_BTDM_CTRL_BR_EDR_MAX_ACL_CONN_EFF=0 \
			CONFIG_BTDM_CTRL_BR_EDR_MAX_SYNC_CONN_EFF=0 \
			CONFIG_BTDM_CTRL_BR_EDR_SCO_DATA_PATH_EFF=0 \
			CONFIG_BTDM_CTRL_PINNED_TO_CORE=0 \
			CONFIG_BT_RESERVE_DRAM=0 \
			CONFIG_COMPILER_OPTIMIZATION_ASSERTIONS_ENABLE=y \
			CONFIG_COMPILER_OPTIMIZATION_LEVEL_DEBUG=y \
			CONFIG_COMPILER_STACK_CHECK_MODE_NONE=y \
			CONFIG_CONSOLE_UART_BAUDRATE=115200 \
			CONFIG_CONSOLE_UART_DEFAULT=y \
			CONFIG_CONSOLE_UART_NUM=0 \
			CONFIG_EFUSE_CODE_SCHEME_COMPAT_3_4=y \
			CONFIG_EFUSE_MAX_BLK_LEN=192 \
			CONFIG_ESP32_APPTRACE_DEST_NONE=y \
			CONFIG_ESP32_APPTRACE_LOCK_ENABLE=y \
			CONFIG_ESP32_BROWNOUT_DET=y \
			CONFIG_ESP32_BROWNOUT_DET_LVL=0 \
			CONFIG_ESP32_BROWNOUT_DET_LVL_SEL_0=y \
			CONFIG_ESP32_DEBUG_OCDAWARE=y \
			CONFIG_ESP32_DEBUG_STUBS_ENABLE=y \
			CONFIG_ESP32_DEEP_SLEEP_WAKEUP_DELAY=2000 \
			CONFIG_ESP32_DEFAULT_CPU_FREQ_240=y \
			CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ=240 \
			CONFIG_ESP32_DEFAULT_PTHREAD_CORE_NO_AFFINITY=y \
			CONFIG_ESP32_DPORT_DIS_INTERRUPT_LVL=5 \
			CONFIG_ESP32_DPORT_WORKAROUND=y \
			CONFIG_ESP32_ENABLE_COREDUMP_TO_NONE=y \
			CONFIG_ESP32_PANIC_PRINT_REBOOT=y \
			CONFIG_ESP32_PHY_CALIBRATION_AND_DATA_STORAGE=y \
			CONFIG_ESP32_PHY_MAX_TX_POWER=20 \
			CONFIG_ESP32_PHY_MAX_WIFI_TX_POWER=20 \
			CONFIG_ESP32_PTHREAD_STACK_MIN=768 \
			CONFIG_ESP32_PTHREAD_TASK_CORE_DEFAULT=-1 \
			CONFIG_ESP32_PTHREAD_TASK_NAME_DEFAULT="pthread" \
			CONFIG_ESP32_PTHREAD_TASK_PRIO_DEFAULT=5 \
			CONFIG_ESP32_PTHREAD_TASK_STACK_SIZE_DEFAULT=3072 \
			CONFIG_ESP32_REDUCE_PHY_TX_POWER=y \
			CONFIG_ESP32_REV_MIN=0 \
			CONFIG_ESP32_REV_MIN_0=y \
			CONFIG_ESP32_RTC_CLK_CAL_CYCLES=1024 \
			CONFIG_ESP32_RTC_CLK_SRC_INT_RC=y \
			CONFIG_ESP32_RTC_CLOCK_SOURCE_INTERNAL_RC=y \
			CONFIG_ESP32_RTC_XTAL_CAL_RETRY=1 \
			CONFIG_ESP32_TIME_SYSCALL_USE_RTC_FRC1=y \
			CONFIG_ESP32_TRACEMEM_RESERVE_DRAM=0x0 \
			CONFIG_ESP32_ULP_COPROC_RESERVE_MEM=0 \
			CONFIG_ESP32_UNIVERSAL_MAC_ADDRESSES=4 \
			CONFIG_ESP32_UNIVERSAL_MAC_ADDRESSES_FOUR=y \
			CONFIG_ESP32_WIFI_AMPDU_RX_ENABLED=y \
			CONFIG_ESP32_WIFI_AMPDU_TX_ENABLED=y \
			CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM=32 \
			CONFIG_ESP32_WIFI_DYNAMIC_TX_BUFFER=y \
			CONFIG_ESP32_WIFI_DYNAMIC_TX_BUFFER_NUM=32 \
			CONFIG_ESP32_WIFI_IRAM_OPT=y \
			CONFIG_ESP32_WIFI_MGMT_SBUF_NUM=32 \
			CONFIG_ESP32_WIFI_NVS_ENABLED=y \
			CONFIG_ESP32_WIFI_RX_BA_WIN=6 \
			CONFIG_ESP32_WIFI_RX_IRAM_OPT=y \
			CONFIG_ESP32_WIFI_SOFTAP_BEACON_MAX_LEN=752 \
			CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM=10 \
			CONFIG_ESP32_WIFI_TASK_PINNED_TO_CORE_0=y \
			CONFIG_ESP32_WIFI_TX_BA_WIN=6 \
			CONFIG_ESP32_WIFI_TX_BUFFER_TYPE=1 \
			CONFIG_ESP32_XTAL_FREQ=40 \
			CONFIG_ESP32_XTAL_FREQ_40=y \
			CONFIG_ESPTOOLPY_AFTER="hard_reset" \
			CONFIG_ESPTOOLPY_AFTER_RESET=y \
			CONFIG_ESPTOOLPY_BAUD_OTHER_VAL=115200 \
			CONFIG_ESPTOOLPY_BEFORE="default_reset" \
			CONFIG_ESPTOOLPY_BEFORE_RESET=y \
			CONFIG_ESPTOOLPY_FLASHFREQ="40m" \
			CONFIG_ESPTOOLPY_FLASHFREQ_40M=y \
			CONFIG_ESPTOOLPY_FLASHMODE="dio" \
			CONFIG_ESPTOOLPY_FLASHMODE_DIO=y \
			CONFIG_ESPTOOLPY_FLASHSIZE="2MB" \
			CONFIG_ESPTOOLPY_FLASHSIZE_2MB=y \
			CONFIG_ESPTOOLPY_FLASHSIZE_DETECT=y \
			CONFIG_ESPTOOLPY_MONITOR_BAUD=115200 \
			CONFIG_ESPTOOLPY_MONITOR_BAUD_115200B=y \
			CONFIG_ESPTOOLPY_MONITOR_BAUD_OTHER_VAL=115200 \
			CONFIG_ESP_CONSOLE_UART_BAUDRATE=115200 \
			CONFIG_ESP_CONSOLE_UART_DEFAULT=y \
			CONFIG_ESP_CONSOLE_UART_NUM=0 \
			CONFIG_ESP_ERR_TO_NAME_LOOKUP=y \
			CONFIG_ESP_EVENT_POST_FROM_IRAM_ISR=y \
			CONFIG_ESP_EVENT_POST_FROM_ISR=y \
			CONFIG_ESP_GRATUITOUS_ARP=y \
			CONFIG_ESP_HTTP_CLIENT_ENABLE_HTTPS=y \
			CONFIG_ESP_INT_WDT=y \
			CONFIG_ESP_INT_WDT_CHECK_CPU1=y \
			CONFIG_ESP_INT_WDT_TIMEOUT_MS=300 \
			CONFIG_ESP_IPC_TASK_STACK_SIZE=1024 \
			CONFIG_ESP_MAIN_TASK_STACK_SIZE=3584 \
			CONFIG_ESP_MAXIMUM_RETRY=3 \
			CONFIG_ESP_SYSTEM_EVENT_QUEUE_SIZE=32 \
			CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE=2304 \
			CONFIG_ESP_TASK_WDT=y \
			CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU0=y \
			CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU1=y \
			CONFIG_ESP_TASK_WDT_TIMEOUT_S=5 \
			CONFIG_ESP_TIMER_TASK_STACK_SIZE=3584 \
			CONFIG_ESP_WIFI_PASS="298 W Audubon Dr" \
			CONFIG_ESP_WIFI_SSID="WAUDUBON" \
			CONFIG_ETH_DMA_BUFFER_SIZE=512 \
			CONFIG_ETH_DMA_RX_BUFFER_NUM=10 \
			CONFIG_ETH_DMA_TX_BUFFER_NUM=10 \
			CONFIG_ETH_PHY_INTERFACE_RMII=y \
			CONFIG_ETH_RMII_CLK_INPUT=y \
			CONFIG_ETH_RMII_CLK_IN_GPIO=0 \
			CONFIG_ETH_USE_ESP32_EMAC=y \
			CONFIG_ETH_USE_SPI_ETHERNET=y \
			CONFIG_FATFS_CODEPAGE=437 \
			CONFIG_FATFS_CODEPAGE_437=y \
			CONFIG_FATFS_FS_LOCK=0 \
			CONFIG_FATFS_LFN_NONE=y \
			CONFIG_FATFS_PER_FILE_CACHE=y \
			CONFIG_FATFS_TIMEOUT_MS=10000 \
			CONFIG_FLASHMODE_DIO=y \
			CONFIG_FMB_CONTROLLER_NOTIFY_QUEUE_SIZE=20 \
			CONFIG_FMB_CONTROLLER_NOTIFY_TIMEOUT=20 \
			CONFIG_FMB_CONTROLLER_STACK_SIZE=4096 \
			CONFIG_FMB_EVENT_QUEUE_TIMEOUT=20 \
			CONFIG_FMB_MASTER_DELAY_MS_CONVERT=200 \
			CONFIG_FMB_MASTER_TIMEOUT_MS_RESPOND=150 \
			CONFIG_FMB_QUEUE_LENGTH=20 \
			CONFIG_FMB_SERIAL_BUF_SIZE=256 \
			CONFIG_FMB_SERIAL_TASK_PRIO=10 \
			CONFIG_FMB_SERIAL_TASK_STACK_SIZE=2048 \
			CONFIG_FMB_TIMER_GROUP=0 \
			CONFIG_FMB_TIMER_INDEX=0 \
			CONFIG_FMB_TIMER_PORT_ENABLED=y \
			CONFIG_FOUR_UNIVERSAL_MAC_ADDRESS=y \
			CONFIG_FREERTOS_ASSERT_FAIL_ABORT=y \
			CONFIG_FREERTOS_ASSERT_ON_UNTESTED_FUNCTION=y \
			CONFIG_FREERTOS_CHECK_MUTEX_GIVEN_BY_OWNER=y \
			CONFIG_FREERTOS_CHECK_STACKOVERFLOW_CANARY=y \
			CONFIG_FREERTOS_CORETIMER_0=y \
			CONFIG_FREERTOS_HZ=100 \
			CONFIG_FREERTOS_IDLE_TASK_STACKSIZE=1536 \
			CONFIG_FREERTOS_INTERRUPT_BACKTRACE=y \
			CONFIG_FREERTOS_ISR_STACKSIZE=1536 \
			CONFIG_FREERTOS_MAX_TASK_NAME_LEN=16 \
			CONFIG_FREERTOS_NO_AFFINITY=0x7FFFFFFF \
			CONFIG_FREERTOS_QUEUE_REGISTRY_SIZE=0 \
			CONFIG_FREERTOS_SUPPORT_STATIC_ALLOCATION=y \
			CONFIG_FREERTOS_TASK_FUNCTION_WRAPPER=y \
			CONFIG_FREERTOS_THREAD_LOCAL_STORAGE_POINTERS=1 \
			CONFIG_FREERTOS_TIMER_QUEUE_LENGTH=10 \
			CONFIG_FREERTOS_TIMER_TASK_PRIORITY=1 \
			CONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH=2048 \
			CONFIG_GARP_TMR_INTERVAL=60 \
			CONFIG_HAGL_HAL_NO_BUFFERING=y \
			CONFIG_HAGL_TJPGD_NEEDS_BYTESWAP=y \
			CONFIG_HEAP_POISONING_DISABLED=y \
			CONFIG_HEAP_TRACING_OFF=y \
			CONFIG_HTTPD_ERR_RESP_NO_DELAY=y \
			CONFIG_HTTPD_MAX_REQ_HDR_LEN=512 \
			CONFIG_HTTPD_MAX_URI_LEN=512 \
			CONFIG_HTTPD_PURGE_BUF_LEN=32 \
			CONFIG_IDF_FIRMWARE_CHIP_ID=0x0000 \
			CONFIG_IDF_TARGET="esp32" \
			CONFIG_IDF_TARGET_ESP32=y \
			CONFIG_INT_WDT=y \
			CONFIG_INT_WDT_CHECK_CPU1=y \
			CONFIG_INT_WDT_TIMEOUT_MS=300 \
			CONFIG_IPC_TASK_STACK_SIZE=1024 \
			CONFIG_IP_LOST_TIMER_INTERVAL=120 \
			CONFIG_LOG_BOOTLOADER_LEVEL=3 \
			CONFIG_LOG_BOOTLOADER_LEVEL_INFO=y \
			CONFIG_LOG_COLORS=y \
			CONFIG_LOG_DEFAULT_LEVEL=3 \
			CONFIG_LOG_DEFAULT_LEVEL_INFO=y \
			CONFIG_LWIP_DHCPS_LEASE_UNIT=60 \
			CONFIG_LWIP_DHCPS_MAX_STATION_NUM=8 \
			CONFIG_LWIP_DHCP_DOES_ARP_CHECK=y \
			CONFIG_LWIP_DHCP_MAX_NTP_SERVERS=1 \
			CONFIG_LWIP_ESP_GRATUITOUS_ARP=y \
			CONFIG_LWIP_GARP_TMR_INTERVAL=60 \
			CONFIG_LWIP_IP4_FRAG=y \
			CONFIG_LWIP_IP6_FRAG=y \
			CONFIG_LWIP_LOCAL_HOSTNAME="espressif" \
			CONFIG_LWIP_LOOPBACK_MAX_PBUFS=8 \
			CONFIG_LWIP_MAX_ACTIVE_TCP=16 \
			CONFIG_LWIP_MAX_LISTENING_TCP=16 \
			CONFIG_LWIP_MAX_RAW_PCBS=16 \
			CONFIG_LWIP_MAX_SOCKETS=10 \
			CONFIG_LWIP_MAX_UDP_PCBS=16 \
			CONFIG_LWIP_NETIF_LOOPBACK=y \
			CONFIG_LWIP_SNTP_UPDATE_DELAY=3600000 \
			CONFIG_LWIP_SO_REUSE=y \
			CONFIG_LWIP_SO_REUSE_RXTOALL=y \
			CONFIG_LWIP_TCPIP_RECVMBOX_SIZE=32 \
			CONFIG_LWIP_TCPIP_TASK_AFFINITY=0x7FFFFFFF \
			CONFIG_LWIP_TCPIP_TASK_AFFINITY_NO_AFFINITY=y \
			CONFIG_LWIP_TCPIP_TASK_STACK_SIZE=3072 \
			CONFIG_LWIP_TCP_MAXRTX=12 \
			CONFIG_LWIP_TCP_MSL=60000 \
			CONFIG_LWIP_TCP_MSS=1440 \
			CONFIG_LWIP_TCP_OVERSIZE_MSS=y \
			CONFIG_LWIP_TCP_QUEUE_OOSEQ=y \
			CONFIG_LWIP_TCP_RECVMBOX_SIZE=6 \
			CONFIG_LWIP_TCP_RTO_TIME=3000 \
			CONFIG_LWIP_TCP_SND_BUF_DEFAULT=5744 \
			CONFIG_LWIP_TCP_SYNMAXRTX=6 \
			CONFIG_LWIP_TCP_WND_DEFAULT=5744 \
			CONFIG_LWIP_TIMERS_ONDEMAND=y \
			CONFIG_LWIP_UDP_RECVMBOX_SIZE=6 \
			CONFIG_MAIN_TASK_STACK_SIZE=3584 \
			CONFIG_MBEDTLS_AES_C=y \
			CONFIG_MBEDTLS_ASYMMETRIC_CONTENT_LEN=y \
			CONFIG_MBEDTLS_CCM_C=y \
			CONFIG_MBEDTLS_CLIENT_SSL_SESSION_TICKETS=y \
			CONFIG_MBEDTLS_ECDH_C=y \
			CONFIG_MBEDTLS_ECDSA_C=y \
			CONFIG_MBEDTLS_ECP_C=y \
			CONFIG_MBEDTLS_ECP_DP_BP256R1_ENABLED=y \
			CONFIG_MBEDTLS_ECP_DP_BP384R1_ENABLED=y \
			CONFIG_MBEDTLS_ECP_DP_BP512R1_ENABLED=y \
			CONFIG_MBEDTLS_ECP_DP_CURVE25519_ENABLED=y \
			CONFIG_MBEDTLS_ECP_DP_SECP192K1_ENABLED=y \
			CONFIG_MBEDTLS_ECP_DP_SECP192R1_ENABLED=y \
			CONFIG_MBEDTLS_ECP_DP_SECP224K1_ENABLED=y \
			CONFIG_MBEDTLS_ECP_DP_SECP224R1_ENABLED=y \
			CONFIG_MBEDTLS_ECP_DP_SECP256K1_ENABLED=y \
			CONFIG_MBEDTLS_ECP_DP_SECP256R1_ENABLED=y \
			CONFIG_MBEDTLS_ECP_DP_SECP384R1_ENABLED=y \
			CONFIG_MBEDTLS_ECP_DP_SECP521R1_ENABLED=y \
			CONFIG_MBEDTLS_ECP_NIST_OPTIM=y \
			CONFIG_MBEDTLS_GCM_C=y \
			CONFIG_MBEDTLS_HARDWARE_AES=y \
			CONFIG_MBEDTLS_HARDWARE_MPI=y \
			CONFIG_MBEDTLS_HARDWARE_SHA=y \
			CONFIG_MBEDTLS_HAVE_TIME=y \
			CONFIG_MBEDTLS_INTERNAL_MEM_ALLOC=y \
			CONFIG_MBEDTLS_KEY_EXCHANGE_DHE_PSK=y \
			CONFIG_MBEDTLS_KEY_EXCHANGE_DHE_RSA=y \
			CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA=y \
			CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_PSK=y \
			CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_RSA=y \
			CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA=y \
			CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_RSA=y \
			CONFIG_MBEDTLS_KEY_EXCHANGE_ELLIPTIC_CURVE=y \
			CONFIG_MBEDTLS_KEY_EXCHANGE_PSK=y \
			CONFIG_MBEDTLS_KEY_EXCHANGE_RSA=y \
			CONFIG_MBEDTLS_KEY_EXCHANGE_RSA_PSK=y \
			CONFIG_MBEDTLS_PEM_PARSE_C=y \
			CONFIG_MBEDTLS_PEM_WRITE_C=y \
			CONFIG_MBEDTLS_PSK_MODES=y \
			CONFIG_MBEDTLS_RC4_DISABLED=y \
			CONFIG_MBEDTLS_SERVER_SSL_SESSION_TICKETS=y \
			CONFIG_MBEDTLS_SSL_ALPN=y \
			CONFIG_MBEDTLS_SSL_IN_CONTENT_LEN=16384 \
			CONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN=4096 \
			CONFIG_MBEDTLS_SSL_PROTO_DTLS=y \
			CONFIG_MBEDTLS_SSL_PROTO_TLS1=y \
			CONFIG_MBEDTLS_SSL_PROTO_TLS1_1=y \
			CONFIG_MBEDTLS_SSL_PROTO_TLS1_2=y \
			CONFIG_MBEDTLS_SSL_RENEGOTIATION=y \
			CONFIG_MBEDTLS_TLS_CLIENT=y \
			CONFIG_MBEDTLS_TLS_ENABLED=y \
			CONFIG_MBEDTLS_TLS_SERVER=y \
			CONFIG_MBEDTLS_TLS_SERVER_AND_CLIENT=y \
			CONFIG_MBEDTLS_X509_CRL_PARSE_C=y \
			CONFIG_MBEDTLS_X509_CSR_PARSE_C=y \
			CONFIG_MB_CONTROLLER_NOTIFY_QUEUE_SIZE=20 \
			CONFIG_MB_CONTROLLER_NOTIFY_TIMEOUT=20 \
			CONFIG_MB_CONTROLLER_STACK_SIZE=4096 \
			CONFIG_MB_EVENT_QUEUE_TIMEOUT=20 \
			CONFIG_MB_MASTER_DELAY_MS_CONVERT=200 \
			CONFIG_MB_MASTER_TIMEOUT_MS_RESPOND=150 \
			CONFIG_MB_QUEUE_LENGTH=20 \
			CONFIG_MB_SERIAL_BUF_SIZE=256 \
			CONFIG_MB_SERIAL_TASK_PRIO=10 \
			CONFIG_MB_SERIAL_TASK_STACK_SIZE=2048 \
			CONFIG_MB_TIMER_GROUP=0 \
			CONFIG_MB_TIMER_INDEX=0 \
			CONFIG_MB_TIMER_PORT_ENABLED=y \
			CONFIG_MDNS_MAX_SERVICES=10 \
			CONFIG_MIPI_DCS_ADDRESS_MODE_BGR=0x08 \
			CONFIG_MIPI_DCS_ADDRESS_MODE_BGR_SELECTED=y \
			CONFIG_MIPI_DCS_ADDRESS_MODE_FLIP_X=0x00 \
			CONFIG_MIPI_DCS_ADDRESS_MODE_FLIP_Y=0x00 \
			CONFIG_MIPI_DCS_ADDRESS_MODE_MIRROR_X=0x00 \
			CONFIG_MIPI_DCS_ADDRESS_MODE_MIRROR_Y=0x00 \
			CONFIG_MIPI_DCS_ADDRESS_MODE_SWAP_XY=0x20 \
			CONFIG_MIPI_DCS_ADDRESS_MODE_SWAP_XY_SELECTED=y \
			CONFIG_MIPI_DCS_PIXEL_FORMAT_16BIT_SELECTED=y \
			CONFIG_MIPI_DISPLAY_DEPTH=16 \
			CONFIG_MIPI_DISPLAY_HEIGHT=240 \
			CONFIG_MIPI_DISPLAY_OFFSET_X=0 \
			CONFIG_MIPI_DISPLAY_OFFSET_Y=0 \
			CONFIG_MIPI_DISPLAY_PIN_BL=4 \
			CONFIG_MIPI_DISPLAY_PIN_CLK=18 \
			CONFIG_MIPI_DISPLAY_PIN_CS=27 \
			CONFIG_MIPI_DISPLAY_PIN_DC=32 \
			CONFIG_MIPI_DISPLAY_PIN_MISO=12 \
			CONFIG_MIPI_DISPLAY_PIN_MOSI=23 \
			CONFIG_MIPI_DISPLAY_PIN_RST=5 \
			CONFIG_MIPI_DISPLAY_PIXEL_FORMAT=0x55 \
			CONFIG_MIPI_DISPLAY_WIDTH=320 \
			CONFIG_MONITOR_BAUD=115200 \
			CONFIG_MONITOR_BAUD_115200B=y \
			CONFIG_MONITOR_BAUD_OTHER_VAL=115200 \
			CONFIG_MQTT_PROTOCOL_311=y \
			CONFIG_MQTT_TRANSPORT_SSL=y \
			CONFIG_MQTT_TRANSPORT_WEBSOCKET=y \
			CONFIG_MQTT_TRANSPORT_WEBSOCKET_SECURE=y \
			CONFIG_NETIF_IP_LOST_TIMER_INTERVAL=120 \
			CONFIG_NEWLIB_STDIN_LINE_ENDING_CR=y \
			CONFIG_NEWLIB_STDOUT_LINE_ENDING_CRLF=y \
			CONFIG_NUMBER_OF_UNIVERSAL_MAC_ADDRESS=4 \
			CONFIG_OPENSSL_ASSERT_EXIT=y \
			CONFIG_OPTIMIZATION_ASSERTIONS_ENABLED=y \
			CONFIG_OPTIMIZATION_LEVEL_DEBUG=y \
			CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="partitions.csv" \
			CONFIG_PARTITION_TABLE_FILENAME="partitions_singleapp.csv" \
			CONFIG_PARTITION_TABLE_MD5=y \
			CONFIG_PARTITION_TABLE_OFFSET=0x8000 \
			CONFIG_PARTITION_TABLE_SINGLE_APP=y \
			CONFIG_POST_EVENTS_FROM_IRAM_ISR=y \
			CONFIG_POST_EVENTS_FROM_ISR=y \
			CONFIG_PTHREAD_DEFAULT_CORE_NO_AFFINITY=y \
			CONFIG_PTHREAD_STACK_MIN=768 \
			CONFIG_PTHREAD_TASK_CORE_DEFAULT=-1 \
			CONFIG_PTHREAD_TASK_NAME_DEFAULT="pthread" \
			CONFIG_PTHREAD_TASK_PRIO_DEFAULT=5 \
			CONFIG_PTHREAD_TASK_STACK_SIZE_DEFAULT=3072 \
			CONFIG_REDUCE_PHY_TX_POWER=y \
			CONFIG_SDK_TOOLPREFIX="xtensa-esp32-elf-" \
			CONFIG_SEMIHOSTFS_HOST_PATH_MAX_LEN=128 \
			CONFIG_SEMIHOSTFS_MAX_MOUNT_POINTS=1 \
			CONFIG_SPIFFS_CACHE=y \
			CONFIG_SPIFFS_CACHE_WR=y \
			CONFIG_SPIFFS_GC_MAX_RUNS=10 \
			CONFIG_SPIFFS_MAX_PARTITIONS=3 \
			CONFIG_SPIFFS_META_LENGTH=4 \
			CONFIG_SPIFFS_OBJ_NAME_LEN=32 \
			CONFIG_SPIFFS_PAGE_CHECK=y \
			CONFIG_SPIFFS_PAGE_SIZE=256 \
			CONFIG_SPIFFS_USE_MAGIC=y \
			CONFIG_SPIFFS_USE_MAGIC_LENGTH=y \
			CONFIG_SPIFFS_USE_MTIME=y \
			CONFIG_SPI_CLOCK_SPEED_HZ=40000000 \
			CONFIG_SPI_FLASH_DANGEROUS_WRITE_ABORTS=y \
			CONFIG_SPI_FLASH_ERASE_YIELD_DURATION_MS=20 \
			CONFIG_SPI_FLASH_ERASE_YIELD_TICKS=1 \
			CONFIG_SPI_FLASH_ROM_DRIVER_PATCH=y \
			CONFIG_SPI_FLASH_SUPPORT_GD_CHIP=y \
			CONFIG_SPI_FLASH_SUPPORT_ISSI_CHIP=y \
			CONFIG_SPI_FLASH_WRITING_DANGEROUS_REGIONS_ABORTS=y \
			CONFIG_SPI_FLASH_YIELD_DURING_ERASE=y \
			CONFIG_SPI_MASTER_ISR_IN_IRAM=y \
			CONFIG_SPI_SLAVE_ISR_IN_IRAM=y \
			CONFIG_STACK_CHECK_NONE=y \
			CONFIG_SUPPORT_STATIC_ALLOCATION=y \
			CONFIG_SUPPORT_TERMIOS=y \
			CONFIG_SUPPRESS_SELECT_DEBUG_OUTPUT=y \
			CONFIG_SYSTEM_EVENT_QUEUE_SIZE=32 \
			CONFIG_SYSTEM_EVENT_TASK_STACK_SIZE=2304 \
			CONFIG_TASK_WDT=y \
			CONFIG_TASK_WDT_CHECK_IDLE_TASK_CPU0=y \
			CONFIG_TASK_WDT_CHECK_IDLE_TASK_CPU1=y \
			CONFIG_TASK_WDT_TIMEOUT_S=5 \
			CONFIG_TCPIP_LWIP=y \
			CONFIG_TCPIP_RECVMBOX_SIZE=32 \
			CONFIG_TCPIP_TASK_AFFINITY=0x7FFFFFFF \
			CONFIG_TCPIP_TASK_AFFINITY_NO_AFFINITY=y \
			CONFIG_TCPIP_TASK_STACK_SIZE=3072 \
			CONFIG_TCP_MAXRTX=12 \
			CONFIG_TCP_MSL=60000 \
			CONFIG_TCP_MSS=1440 \
			CONFIG_TCP_OVERSIZE_MSS=y \
			CONFIG_TCP_QUEUE_OOSEQ=y \
			CONFIG_TCP_RECVMBOX_SIZE=6 \
			CONFIG_TCP_SND_BUF_DEFAULT=5744 \
			CONFIG_TCP_SYNMAXRTX=6 \
			CONFIG_TCP_WND_DEFAULT=5744 \
			CONFIG_TIMER_QUEUE_LENGTH=10 \
			CONFIG_TIMER_TASK_PRIORITY=1 \
			CONFIG_TIMER_TASK_STACK_DEPTH=2048 \
			CONFIG_TIMER_TASK_STACK_SIZE=3584 \
			CONFIG_TOOLPREFIX="xtensa-esp32-elf-" \
			CONFIG_TRACEMEM_RESERVE_DRAM=0x0 \
			CONFIG_UDP_RECVMBOX_SIZE=6 \
			CONFIG_ULP_COPROC_RESERVE_MEM=0 \
			CONFIG_UNITY_ENABLE_DOUBLE=y \
			CONFIG_UNITY_ENABLE_FLOAT=y \
			CONFIG_UNITY_ENABLE_IDF_TEST_RUNNER=y \
			CONFIG_VFS_SUPPORT_TERMIOS=y \
			CONFIG_VFS_SUPPRESS_SELECT_DEBUG_OUTPUT=y \
			CONFIG_WEATHER_API_KEY="0e40f74ecc24c41f6df71c302267dfba" \
			CONFIG_WEATHER_CITY="Shepherdsville, KY" \
			CONFIG_WEATHER_LATITUDE="37.98" \
			CONFIG_WEATHER_LONGITUDE="-85.71" \
			CONFIG_WEATHER_METRIC_UNITS=y \
			CONFIG_WIFI_PROV_AUTOSTOP_TIMEOUT=30 \
			CONFIG_WIFI_PROV_SCAN_MAX_ENTRIES=16 \
			CONFIG_WL_SECTOR_SIZE=4096 \
			CONFIG_WL_SECTOR_SIZE_4096=y \
			CONFIG_WPA_MBEDTLS_CRYPTO=y 

DISTFILES += \
    README.md \
    .gitignore \
    .gitmodules